### PR TITLE
Fix build and tests

### LINKED ISSUE #443: Changes in PR #435 to make FQDN for StausCodes breaks test in PR #434
The above two PRs appear to have been merged into master, although he second is breaking a test in the first: 

> Test that fully qualified names are used

`httpClient.fetch(req)({
             case org.http4s.Status.Ok(resp) =>
               F.map(getUserOkDecoder.decode(resp, strict = false).value.flatMap(F.fromEither))(GetUserResponse.Ok.apply)
             case resp =>
               F.raiseError(UnexpectedStatus(resp.status))
})`

`org.http4s.Status.Ok(resp)` should become `_root_.org.http4s.Status.Ok(resp)`, however I'm raising this issue to understand what problem existed by just using the FQDN for `org.http4s.Status.Ok`

### PR DESCRIPTION
**Pull request by blast-hardcheese**
Resolves #443 

So, master started failing to compile after merging #434 due to some Scala-specific changes being applied directly in the "core" interpreter. This wasn't caught earlier because the Java tests haven't been run during the PR validation process.

- [x] Switching from `scalaTestSuite` to `testSuite` in travis and github actions
- [x] Adding `codegen:test` formatting check
- [x] Moving `_root_` package prefix to `ScalaGenerator` (identity in `JavaGenerator`)
- [x] Only add `definitions` imports if there are actually definitions (avoid errors during Java codegen if there are no definitions)

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

File: modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala [hunk 1]
```diff
@@ -398,7 +400,7 @@ object ScalaGenerator {
               ..${extraImports}
               import ${buildPkgTerm(List("_root_") ++ pkgName ++ List("Implicits"))}._
               ..${frameworkImplicitName.map(name => q"import ${buildPkgTerm(List("_root_") ++ pkgName)}.${name}._")}
-              import ${buildPkgTerm(List("_root_") ++ dtoComponents)}._
+              ..${dtoComponents.map(x => q"import ${buildPkgTerm(List("_root_") ++ x)}._")}
```
Comment (tomasherman) [inline modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala]: as a side note - i think this is the main reason we are having trouble with swagger definitions named `Option` etc ... if we avoided these imports and used fully qualified imports in the generated code, we would be safe - think

Comment (blast-hardcheese) [reply modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala]: Yeah; After the qualified DTO PR was merged, I actually don't think this explicit import is even required anymore, other than people using `x-scala-type: List[Foo]`, not having a good way to do effectively `x-scala-type: List[#/definitions/Foo]`
