### PR TITLE
don't constrain x-scala-type in params to Type.Name.  fixes #214

### LINKED ISSUE #214: x-scala-type doesn't accept qualified names in paths section
I can use `x-scala-type: SomeType` in both parameters and definitions.  I can also use `x-scala-type: some.qualified.Type` in definitions -- but not in parameters.  Using that in parameters crashes guardrail:

```
Error: Error attempting to process src/main/resources/swagger-specs/swagger.yaml:

scala.MatchError: some.qualified.Type (of class scala.meta.Type$Select$TypeSelectImpl)
        at com.twilio.guardrail.SwaggerUtil$paths$akkaExtractor$$anonfun$$lessinit$greater$1.$anonfun$apply$9(SwaggerUtil.scala:467)
          ...
        at com.twilio.guardrail.SwaggerUtil$paths$akkaExtractor$$anonfun$$lessinit$greater$1.apply(SwaggerUtil.scala:470)
        at com.twilio.guardrail.SwaggerUtil$paths$akkaExtractor$$anonfun$$lessinit$greater$1.apply(SwaggerUtil.scala:456)
        at com.twilio.guardrail.SwaggerUtil$paths$Extractors.$anonfun$regexSegment$4(SwaggerUtil.scala:419)
        at com.twilio.guardrail.SwaggerUtil$paths$.$anonfun$lookupName$3(SwaggerUtil.scala:367)
          ...

        at com.twilio.guardrail.SwaggerUtil$paths$.com$twilio$guardrail$SwaggerUtil$paths$$lookupName(SwaggerUtil.scala:367)
        at com.twilio.guardrail.SwaggerUtil$paths$Extractors.$anonfun$regexSegment$3(SwaggerUtil.scala:413)
        at com.twilio.guardrail.SwaggerUtil$paths$Extractors.runParse(SwaggerUtil.scala:446)
        at com.twilio.guardrail.SwaggerUtil$paths$.generateUrlAkkaPathExtractors(SwaggerUtil.scala:532)
        at com.twilio.guardrail.generators.AkkaHttpServerGenerator$ServerTermInterp$.pathStrToAkka(AkkaHttpServerGenerator.scala:207)
        at com.twilio.guardrail.generators.AkkaHttpServerGenerator$ServerTermInterp$.$anonfun$generateRoute$10(AkkaHttpServerGenerator.scala:586)
        at com.twilio.guardrail.generators.AkkaHttpServerGenerator$ServerTermInterp$.$anonfun$generateRoute$9(AkkaHttpServerGenerator.scala:585)
        at com.twilio.guardrail.generators.AkkaHttpServerGenerator$ServerTermInterp$.$anonfun$generateRoute$2(AkkaHttpServerGenerator.scala:560)
        at com.twilio.guardrail.generators.AkkaHttpServerGenerator$ServerTermInterp$.generateRoute(AkkaHttpServerGenerator.scala:558)
        ...
```

### PR DESCRIPTION
**Pull request by dsilvasc**
We can use x-scala-type: SomeType in both parameters and definitions. We can also use x-scala-type: some.qualified.Type in definitions -- but not in parameters. Using that in parameters crashes guardrail.

This change relaxes the match that was crashing.

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [x] I acknowlege that all my contributions will be made under the project's license.

### CODE REVIEW

File: modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala [hunk 1]
```diff
@@ -550,7 +550,7 @@ object SwaggerUtil {
                   case t"Int"        => Right(p"IntVar(${Pat.Var(paramName)})")
                   case t"Long"       => Right(p"LongVar(${Pat.Var(paramName)})")
                   case t"BigInt"     => Right(p"BigIntVar(${Pat.Var(paramName)})")
-                  case tpe @ Type.Name(_) =>
+                  case tpe =>
```
Comment (blast-hardcheese) [inline modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala]: Actually, I'm realizing that this is not going to work -- This code was previously string-interpolating the type name here, so this'll need a little more finesse. Just a minute.

File: modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala [hunk 2]
```diff
@@ -550,8 +550,13 @@ object SwaggerUtil {
                   case t"Int"        => Right(p"IntVar(${Pat.Var(paramName)})")
                   case t"Long"       => Right(p"LongVar(${Pat.Var(paramName)})")
                   case t"BigInt"     => Right(p"BigIntVar(${Pat.Var(paramName)})")
-                  case tpe @ Type.Name(_) =>
+                  case Type.Name(tpe) =>
                     Right(p"${Term.Name(s"${tpe}Var")}(${Pat.Var(paramName)})")
+                  case Type.Select(_, Type.Name(tpe)) =>
+                    Right(p"${Term.Name(s"${tpe}Var")}(${Pat.Var(paramName)})")
+                  case tpe =>
+                    println(s"Error: Unsure how to map ${tpe} into an extractor")
```
Comment (blast-hardcheese) [inline modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala]: This is necessary because atto eats the error string before we get here
